### ISSUE TITLE
System.InvalidOperationException: Wire Type is invalid

### ISSUE THREAD

**Issue by mcheung610** [lightstep/lightstep-tracer-csharp#72]
Does anyone know why I am getting this error? I am following the example and setup my tracer. Things look pretty straightforward so far. 

```
var satelliteOptions = new SatelliteOptions(collectorHost, 80, true);
var overrideTags = new Dictionary<string, object>
{
   {LightStepConstants.ComponentNameKey, $"{serviceName}-{GetEnvironmentName()}-{region}"}
};
var tracerOptions = new Options(token).WithSatellite(satelliteOptions).WithTags(overrideTags);
var tracer = new Tracer(tracerOptions);
```

Stacktrace
```
System.InvalidOperationException: Wire Type is invalid.    
at Google.Protobuf.UnknownFieldSet.MergeFieldFrom(CodedInputStream input)    
at Google.Protobuf.UnknownFieldSet.MergeFieldFrom(UnknownFieldSet unknownFields, CodedInputStream input)    
at LightStep.Collector.ReportResponse.MergeFrom(CodedInputStream input)    
at Google.Protobuf.MessageExtensions.MergeFrom(IMessage message, Stream input, Boolean discardUnknownFields)    
at Google.Protobuf.MessageParser`1.ParseFrom(Stream input)   
at LightStep.Collector.LightStepHttpClient.SendReport(ReportRequest report)
```

**Comment by austinlparker** [comment]
It looks like it's failing to deserialize the response from the LightStep Satellite. Are you getting this message all the time?

**Comment by mcheung610** [comment]
Yes. I am getting this message all the time.

**Comment by austinlparker** [comment]
Are you using a local developer satellite, or is someone else managing it? My gut would be that you're getting something unexpected in the response (so either it's behind a load balancer and you're getting a response from the LB that's not a valid `ReportResponse`) or there's some weird auth thing going on. You might want to reach out and file a support request through LightStep because there's probably account information that would be helpful in diagnosing your issue.

**Comment by austinlparker** [comment]
Closed for inactivity
