### ISSUE TITLE
Reduce the verbosity of logs

### ISSUE THREAD

**Issue by BhuvanB** [lightstep/lightstep-tracer-csharp#86]
The tracer seems to be logging to INFO every 5 seconds. This is overwhelming many users log destinations. The workaround is to blackhole this source for INFO, but it's not really a good idea to just ignore a logging level for good in the long term.

**Comment by austinlparker** [comment]
I'll do a pass on this for the next release

**Comment by austinlparker** [comment]
Do you know what, specifically, is logging at info at that level? There's a lot of stuff at trace, but only one thing at info and it shouldn't be getting enabled...

**Comment by hotchkj** [comment]
For what it's worth, I notice a lot of these at Serilog's Debug level, not Trace, for example: https://github.com/lightstep/lightstep-tracer-csharp/blob/bdb38ba67e7cdd02c4b120490f29f3ae87b86027/src/LightStep/Collector/LightStepHttpClient.cs#L161

It's possible log levels have got confused over time. LibLog is now [discontinued](https://github.com/damianh/LibLog/issues/270) and it's worth noting that Microsoft define [Trace as lowest level](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#log-level) below Debug:

LogLevel | Value | Method | Description
-- | -- | -- | --
Trace | 0 | LogTrace | Contain the most detailed messages. These messages may contain  sensitive app data. These messages are disabled by default and should not be enabled in production.
Debug | 1 | LogDebug | For debugging and development. Use with caution in production due to the high volume.
Information | 2 | LogInformation | Tracks the general flow of the app. May have long-term value.

For the many many timer messages, Debug logs do get swamped with these today and it'd be preferable to have them at what maps to Trace level (or Verbose in Serilog terms).

Hope that helps.
